name: Production & Deploy
on:
  pull_request:
    types: closed 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Production Os-Inventory
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.PROD_SSH_USERNAME}} # User of the server you want to ssh into
          host: ${{secrets.PROD_SSH_HOST}} # IP address of the server you wish to ssh into
          port: ${{secrets.PROD_SSH_PORT}} # Port address of the server you wish to ssh into
          password: ${{secrets.PROD_SSH_PASSWORD}} # Password of the user of the server you want to ssh into

          script: |
            cd domains/demo.omega.ac/public_html/api

            git pull

            composer2 update
            composer install --optimize-autoloader --no-dev

            php artisan migrate
            php artisan optimize:clear
